services:
  bookingapi:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: BookingApi/Dockerfile
    depends_on:
      - postgres
    environment:
      - SQL_ConnectionString=Host=postgres;Port=5432;Database=Booking;Username=postgres;Password=Passw0rd;

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=Booking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: